#!/bin/bash
# Design-language ratchet for docs/DESIGN.md.
#
# Counts known deviations per file under Sources/Views (DesignSystem.swift and
# GlassSystem.swift own the tokens and glass helpers and are exempt) and compares
# them with script/design_lint_baseline.txt. A rising count fails; a falling count
# also fails until the baseline is lowered with `script/design_lint.sh --update`,
# so the baseline only moves down. Shell only, so it runs without a Swift toolchain.
set -euo pipefail

cd "$(dirname "$0")/.."
BASELINE="script/design_lint_baseline.txt"
export LC_ALL=C

# rule name | extended regular expression
RULES=(
    "literal-font-size|\.system\(size:"
    "literal-color|(^|[^A-Za-z0-9_])Color\.[A-Za-z]+|[(,:] ?\.(black|blue|brown|cyan|gray|green|indigo|mint|orange|pink|purple|red|teal|white|yellow)[^A-Za-z0-9_]|Color\((red|white|hue|\.sRGB|\.displayP3)"
    "corner-radius|\.cornerRadius\("
    "toolbar-background|toolbarBackground"
    "direct-glass|glassEffect|GlassEffectContainer"
    "scroll-edge-style|scrollEdgeEffectStyle"
    "uppercased|\.uppercased\(\)"
    "material|\.(ultraThin|thin|regular|thick|ultraThick)Material"
)
ALLOWED_COLORS='Color\.(clear|primary|secondary|accentColor)$'

count() {
    local rule="$1" pattern="$2" file="$3"
    if [[ "$rule" == "literal-color" ]]; then
        { grep -o -E "$pattern" "$file" || true; } | { grep -v -E "$ALLOWED_COLORS" || true; } | wc -l | tr -d ' '
    else
        { grep -o -E "$pattern" "$file" || true; } | wc -l | tr -d ' '
    fi
}

current="$(mktemp)"
trap 'rm -f "$current"' EXIT

find Sources/Views -name '*.swift' ! -name DesignSystem.swift ! -name GlassSystem.swift | sort | while read -r file; do
    for entry in "${RULES[@]}"; do
        rule="${entry%%|*}"
        pattern="${entry#*|}"
        n="$(count "$rule" "$pattern" "$file")"
        if [[ "$n" -gt 0 ]]; then
            printf '%s %s %s\n' "$rule" "$file" "$n"
        fi
    done
done | sort > "$current"

# Phase 4 (#354): a permanent zero-deviation gate for content styles.
if grep -E '^(literal-font-size|literal-color|uppercased) ' "$current"; then
    echo "Design lint: literal fonts, colors and uppercasing must be zero (#354)." >&2
    exit 1
fi

if [[ "${1:-}" == "--update" ]]; then
    {
        echo "# Design lint baseline: rule file count. Generated by script/design_lint.sh --update."
        echo "# Counts may only go down; see docs/DESIGN.md before adding an exception."
        cat "$current"
    } > "$BASELINE"
    echo "Design lint baseline updated ($(wc -l < "$current" | tr -d ' ') entries)."
    exit 0
fi

if [[ ! -f "$BASELINE" ]]; then
    echo "Design lint: missing $BASELINE; run script/design_lint.sh --update." >&2
    exit 1
fi

grep -v '^#' "$BASELINE" | awk -v current="$current" '
    { base[$1 " " $2] = $3 }
    END {
        while ((getline line < current) > 0) {
            split(line, f, " ")
            key = f[1] " " f[2]
            now[key] = f[3]
        }
        status = 0
        for (key in now) {
            b = (key in base) ? base[key] : 0
            if (now[key] > b) {
                printf "Design lint: %s rose from %d to %d. Use the DESIGN.md token or helper instead.\n", key, b, now[key]
                status = 1
            }
        }
        for (key in base) {
            n = (key in now) ? now[key] : 0
            if (n < base[key]) {
                printf "Design lint: %s fell from %d to %d. Lower the baseline with script/design_lint.sh --update.\n", key, base[key], n
                status = 1
            }
        }
        exit status
    }
' >&2 || exit 1

echo "Design lint passed ($(awk '{ total += $3 } END { print total + 0 }' "$current") baseline deviations remaining)."
